baseurl = "http://sonhnguyen.github.io/"
languageCode = "en-us"
title = "Son Nguyen's blog"
theme= "hugo-theme-geppaku"
googleAnalytics = ""
disqusShortname = "sonhnguyen"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Son Nguyen"

    # Please set account ids
    # This is Optional values
    linkedin = "nhson"
    github   = "sonhnguyen"

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        #twitter  = false
        #facebook = true
        # hatena   = true # hatena is Japanese social media
        #google   = true
        #pocket   = true
        #Please set id when you want to display facebook
        #facebookAppId = "your app id"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        #sidebar = "adsense/sidebar.html"
        #content = "adsense/content.html"
